# Generated by Django 3.1.7 on 2021-03-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=64)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('source', models.URLField()),
                ('image', models.CharField(max_length=256)),
            ],
        ),
    ]
